go:
  version: 1.14
  cgo: false
repository:
    path: github.com/galexrt/srcds_controller
build:
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
    binaries:
        - name: sc
          path: ./cmd/sc
        - name: srcds_controller
          path: ./cmd/srcds_controller
        - name: srcds_cmdrelay
          path: ./cmd/srcds_cmdrelay
        - name: srcds_runner
          path: ./cmd/srcds_runner
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        #- linux/386
        #- darwin/amd64
        #- darwin/386
        #- windows/amd64
        #- windows/386
        #- freebsd/amd64
        #- freebsd/386
        #- openbsd/amd64
        #- openbsd/386
        #- netbsd/amd64
        #- netbsd/386
        #- dragonfly/amd64
        #- linux/arm
        #- linux/arm64
        #- freebsd/arm
        #- openbsd/arm
        #- linux/mips64
        #- linux/mips64le
        #- netbsd/arm
        #- linux/ppc64
        #- linux/ppc64le
