general:
  runOptions:
    #uid: 1001
    #gid: 1001
  umask: 7
docker:
  image: galexrt/srcds_controller:runner-latest
  namePrefix: "game-"
server:
  name: testserver123
  address: 127.0.0.1
  port: 27015
  flags:
    - -console
    - -game garrysmod
  #runOptions:
  #  uid: 1001
  #  gid: 1001
  onExitCommand: quit
  enabled: true
  rcon:
    password: YOUR_RCON_PASSWORD
  gameID: 4020
  resources: {}
    #cpusetcpus: "0,1"
  checks:
    - name: rcon
      limit:
        after: 7m
        count: 1
        actions:
          - RESTART
checker:
  interval: 30s
  splay:
    start: 0
    end: 15
checks:
  rcon:
    timeout: 12s
