general:
  runOptions:
    #uid: 1001
    #gid: 1001
  umask: 7
docker:
  image: galexrt/srcds_controller:runner-latest
  namePrefix: "game-"
  additionalMounts: []
  # /usr/share/zoneinfo/Europe/Berlin
  timezoneFile: ""
server:
  name: testserver123
  address: 127.0.0.1
  port: 27015
  command: ./srcds_run
  flags:
    - -console
    - -game garrysmod
    - -port %SERVER_PORT%
    - +map %MAP_RANDOM%
  mapSelection:
    enabled: true
    fileFilter: "./garrysmod/maps/rp_*.bsp"
    fallbackMap: gm_construct
  mountsDir: /home/gameserver/mount
  onExitCommand: quit
  enabled: true
  rcon:
    password: YOUR_RCON_PASSWORD
  gameID: 4020
  resources: {}
    #cpusetcpus: "0,1"
  acl:
    users:
      - 1000
    groups:
      - 1000
  checks:
    - name: rcon
      limit:
        after: 7m
        count: 1
        actions:
          - RESTART
        actionOpts: {}
  steamCMDDir: /home/gameserver/steamcmd
checker:
  interval: 30s
  splay:
    start: 0
    end: 15
