docker:
  image: galexrt/srcds_controller:runner-latest
  namePrefix: "game"
servers:
  # name must be unique
  - name: YOUR_SERVER_NAME
    address: 127.0.0.1
    port: 27015
    path: YOUR_SERVER_PATH # Used as the current working directory of the commands executed
    flags:
      - -console
      - -game garrysmod
    runOptions:
      #uid: 1001
      #gid: 1001
    onExitCommand: quit
    rcon:
      password: YOUR_RCON_PASSWORD
    checks:
      - name: rcon
        opts:
          password: YOUR_RCON_PASSWORD
        limit:
          after: 10m
          count: 1
          actions:
            - RESTART
checker:
  interval: 30s
  splay:
    start: 0
    end: 15
checks:
  rcon:
    timeout: 12s
