general:
  umask: 7
docker:
  image: "galexrt/srcds_controller:runner-latest"
  localTimeFile: "/etc/localtime"
  timezoneFile: "/etc/timezone"
  additionalEnvVars:
    - "TZ=UTC"
checks:
  rcon:
    timeout: 12s
  actioreactio:
    timeout: 10s
